version: '3'

services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'apidevbills'
      MONGO_INITDB_ROOT_PASSWORD: 'api123'
    ports:
      - '27017:27017'
    networks:
      - local  
    
          
  app: 
    depends_on:
      - mongo
    container_name: api-devbills
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/app
      -  /home/app/node_modules
      - ./:/home/app/node_modules  
    ports:  
      - '3335:3335'
    networks:
      - local  
    
networks:
  local:
    name: local
      
   
